<a href="https://colab.research.google.com/github/SantiagoCar256/Prueba/blob/main/Metodo_Newton-Raphson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Método de Newton-Raphson
# Ejemplo 1 (Burden ejemplo 1 p.51/pdf.61)

import numpy as np

# INGRESO
fx  = lambda x: np.cos(x) - (x**2)
dfx = lambda x: (-1*(np.sin(x)))-(2*x)

x0 = -
  0.5
tolera = 0.00001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[5.0000e-01 9.2421e-01 4.2421e-01]
 [9.2421e-01 8.2911e-01 9.5101e-02]
 [8.2911e-01 8.2415e-01 4.9596e-03]
 [8.2415e-01 8.2413e-01 1.3819e-05]
 [8.2413e-01 8.2413e-01 1.0739e-10]]
raiz en:  0.8241323123025224
con error de:  1.0738998579284953e-10
